Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  
  ####################
  # Snippets to use
  ####################
  
  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true
  
  ####################
  ####################
  
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  
  #Puppet master
  config.vm.define "dnspuppetserver".to_sym do |dnspuppetserver_config|
    dnspuppetserver_config.vm.box = "centos-7.1-amd64-vmware"
    dnspuppetserver_config.vm.network :private_network, ip: "10.0.2.10"
    dnspuppetserver_config.vm.hostname = "dnspuppetserver.local"
    dnspuppetserver_config.hostmanager.aliases = %w(puppet dnspuppetserver.local puppetexplorer.dnspuppetserver.local puppetboard.dnspuppetserver.local)
    #set some machine-specific options
    dnspuppetserver_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
      v.vm.network :private_network, ip: "10.0.1.10"
    end
    config.vm.provider "vmware_fusion" do |v, override|
      v.vmx["memsize"] = "1024"
      v.vmx["numvcpus"] = "1"
    end
    #NFS folder sharing for Puppet modules and manifests
    dnspuppetserver_config.vm.synced_folder "production/", "/etc/puppetlabs/code/environments/production", :nfs => true
    dnspuppetserver_config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppetlabs/code/environments/production/modules", :nfs => true
    #dnspuppetserver_config.vm.synced_folder "hieradata/", "/etc/puppetlabs/code/environments/production/hieradata", :nfs => true
    #dnspuppetserver_config.vm.synced_folder "files/", "/etc/puppet/files", :nfs => true
    #Puppet master provisioning script
    dnspuppetserver_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet4_server.sh"
  end

  #A CentOS BIND DNS master server
  config.vm.define "dnsserver1".to_sym do |dnsserver1_config|
    dnsserver1_config.vm.box = "centos-7.1-amd64-vmware"
    dnsserver1_config.vm.network :private_network, ip: "10.0.2.11"
    dnsserver1_config.vm.hostname = "dnsserver1.local"
    dnsserver1_config.hostmanager.aliases = "dnsserver1.local"
    #set some machine-specific options
    dnsserver1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
      v.vm.network :private_network, ip: "10.0.1.11"
    end
    config.vm.provider "vmware_fusion" do |v, override|
      v.vmx["memsize"] = "256"
      v.vmx["numvcpus"] = "1"
    end
    #NFS folder sharing for Puppet modules and manifests
    #dnsserver1_config.vm.synced_folder ".", "/vagrant", :nfs => true
    dnsserver1_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet4_agent.sh"
  end

  #A CentOS BIND DNS master server
  config.vm.define "dnsserver2".to_sym do |dnsserver2_config|
    dnsserver2_config.vm.box = "centos-7.1-amd64-vmware"
    dnsserver2_config.vm.network :private_network, ip: "10.0.2.12"
    dnsserver2_config.vm.hostname = "dnsserver2.local"
    dnsserver2_config.hostmanager.aliases = "dnsserver2.local"
    #set some machine-specific options
    dnsserver2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
      v.vm.network :private_network, ip: "10.0.1.12"
    end
    config.vm.provider "vmware_fusion" do |v, override|
      v.vmx["memsize"] = "256"
      v.vmx["numvcpus"] = "1"
    end
    #NFS folder sharing for Puppet modules and manifests
    #dnsserver2_config.vm.synced_folder ".", "/vagrant", :nfs => true
    dnsserver2_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet4_agent.sh"
  end

  #A CentOS BIND DNS replica server
  config.vm.define "dnsreplica1".to_sym do |dnsreplica1_config|
    dnsreplica1_config.vm.box = "centos-7.1-amd64-vmware"
    dnsreplica1_config.vm.network :private_network, ip: "10.0.2.13"
    dnsreplica1_config.vm.hostname = "dnsreplica1.local"
    dnsreplica1_config.hostmanager.aliases = "dnsreplica1.local"
    #set some machine-specific options
    dnsreplica1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
      v.vm.network :private_network, ip: "10.0.1.13"
    end
    config.vm.provider "vmware_fusion" do |v, override|
      v.vmx["memsize"] = "256"
      v.vmx["numvcpus"] = "1"
    end
    #NFS folder sharing for Puppet modules and manifests
    #dnsreplica1_config.vm.synced_folder ".", "/vagrant", :nfs => true
    dnsreplica1_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet4_agent.sh"
  end

  #A CentOS BIND DNS replica server
  config.vm.define "dnsreplica2".to_sym do |dnsreplica2_config|
    dnsreplica2_config.vm.box = "centos-7.1-amd64-vmware"
    dnsreplica2_config.vm.network :private_network, ip: "10.0.2.14"
    dnsreplica2_config.vm.hostname = "dnsreplica2.local"
    dnsreplica2_config.hostmanager.aliases = "dnsreplica2.local"
    #set some machine-specific options
    dnsreplica2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
      v.vm.network :private_network, ip: "10.0.1.14"
    end
    config.vm.provider "vmware_fusion" do |v, override|
      v.vmx["memsize"] = "256"
      v.vmx["numvcpus"] = "1"
    end
    #NFS folder sharing for Puppet modules and manifests
    #dnsreplica2_config.vm.synced_folder ".", "/vagrant", :nfs => true
    dnsreplica2_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet4_agent.sh"
  end

  #A CentOS BIND DNS subdomain server
  config.vm.define "dnssubserver1".to_sym do |dnssubserver1_config|
    dnssubserver1_config.vm.box = "centos-7.1-amd64-vmware"
    dnssubserver1_config.vm.network :private_network, ip: "10.0.2.15"
    dnssubserver1_config.vm.hostname = "dnssubserver1.local"
    dnssubserver1_config.hostmanager.aliases = "dnssubserver1.local"
    #set some machine-specific options
    dnssubserver1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
      v.vm.network :private_network, ip: "10.0.1.15"
    end
    config.vm.provider "vmware_fusion" do |v, override|
      v.vmx["memsize"] = "256"
      v.vmx["numvcpus"] = "1"
    end
    #NFS folder sharing for Puppet modules and manifests
    #dnssubserver1_config.vm.synced_folder ".", "/vagrant", :nfs => true
    dnssubserver1_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet4_agent.sh"
  end

  #A CentOS BIND DNS subdomain server
  config.vm.define "dnssubserver2".to_sym do |dnssubserver2_config|
    dnssubserver2_config.vm.box = "centos-7.1-amd64-vmware"
    dnssubserver2_config.vm.network :private_network, ip: "10.0.2.16"
    dnssubserver2_config.vm.hostname = "dnssubserver2.local"
    dnssubserver2_config.hostmanager.aliases = "dnssubserver2.local"
    #set some machine-specific options
    dnssubserver2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
      v.vm.network :private_network, ip: "10.0.1.16"
    end
    config.vm.provider "vmware_fusion" do |v, override|
      v.vmx["memsize"] = "256"
      v.vmx["numvcpus"] = "1"
    end
    #NFS folder sharing for Puppet modules and manifests
    #dnssubserver2_config.vm.synced_folder ".", "/vagrant", :nfs => true
    dnssubserver2_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet4_agent.sh"
  end

  #A CentOS 7 Icinga 2, Riemann/InfluxDB/Grafana and Elasticsearch/Logstash/Heka/Kibana server:
  config.vm.define "dnsmonitoring".to_sym do |dnsmonitoring_config|
    dnsmonitoring_config.vm.box = "centos-7.1-amd64-vmware"
    dnsmonitoring_config.vm.network :private_network, ip: "10.0.2.20"
    dnsmonitoring_config.vm.hostname = "dnsmonitoring.local"
    dnsmonitoring_config.hostmanager.aliases = "dnsmonitoring.local"
    #set some machine-specific options
    dnsmonitoring_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
      v.vm.network :private_network, ip: "10.0.1.20"
    end
    config.vm.provider "vmware_fusion" do |v, override|
      v.vmx["memsize"] = "256"
      v.vmx["numvcpus"] = "1"
    end
    #NFS folder sharing for Puppet modules and manifests
    #dnsmonitoring_config.vm.synced_folder ".", "/vagrant", :nfs => true
    dnsmonitoring_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet4_agent.sh"
  end

end
