Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  
  ####################
  # Snippets to use
  ####################
  
  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true
  
  ####################
  ####################
  
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  
  #Puppet master
  config.vm.define "dnspuppetserver".to_sym do |dnspuppetserver_config|
    dnspuppetserver_config.vm.box = "centos-7.1-amd64-vmware"
    dnspuppetserver_config.vm.network :private_network, ip: "10.0.2.10"
    dnspuppetserver_config.vm.hostname = "dnspuppetserver.local"
    dnspuppetserver_config.hostmanager.aliases = %w(puppet dnspuppetserver.local puppetexplorer.dnspuppetserver.local puppetboard.dnspuppetserver.local)
    #set some machine-specific options
    dnspuppetserver_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
      v.vm.network :private_network, ip: "10.0.1.10"
    end
    config.vm.provider "vmware_fusion" do |v, override|
      v.vmx["memsize"] = "1024"
      v.vmx["numvcpus"] = "1"
    end
    #NFS folder sharing for Puppet modules and manifests
    dnspuppetserver_config.vm.synced_folder "production/", "/etc/puppetlabs/code/environments/production", :nfs => true
    dnspuppetserver_config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppetlabs/code/environments/production/modules", :nfs => true
    #dnspuppetserver_config.vm.synced_folder "hieradata/", "/etc/puppetlabs/code/environments/production/hieradata", :nfs => true
    #dnspuppetserver_config.vm.synced_folder "files/", "/etc/puppet/files", :nfs => true
    #Puppet master provisioning script
    dnspuppetserver_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet4_server.sh"
  end

  #A CentOS BIND DNS master server
  config.vm.define "dnsserver1".to_sym do |dnsserver1_config|
    dnsserver1_config.vm.box = "centos-7.1-amd64-vmware"
    dnsserver1_config.vm.network :private_network, ip: "10.0.2.11"
    dnsserver1_config.vm.hostname = "dnsserver1.local"
    dnsserver1_config.hostmanager.aliases = "dnsserver1.local"
    #set some machine-specific options
    dnsserver1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
      v.vm.network :private_network, ip: "10.0.1.11"
    end
    config.vm.provider "vmware_fusion" do |v, override|
      v.vmx["memsize"] = "256"
      v.vmx["numvcpus"] = "1"
    end
    #NFS folder sharing for Puppet modules and manifests
    #dnsserver1_config.vm.synced_folder ".", "/vagrant", :nfs => true
    dnsserver1_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet4_agent.sh"
  end
end
