Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true

  #A CentOS 7 VMware machine:
  config.vm.define "centos7".to_sym do |centos7_config|
    centos7_config.vm.box = "centos-7.1-amd64-vmware"
    centos7_config.vm.hostname = "centos7.local"
    centos7_config.vm.network :private_network, ip: "10.0.2.2"
    #Set some machine-specific options for either Virtualbox or VMWare:
    centos7_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM
      v.customize ["modifyvm", :id, "--memory", "256"]
      v.gui = false
    end
    config.vm.provider "vmware_fusion" do |v, override|
      #override.vm.provision "shell", inline: "sudo /sbin/ifdown ens33; sudo /sbin/ifup ens33;"
      v.vmx["memsize"] = "256"
      v.vmx["numvcpus"] = "1"
    end
  end

  #A CentOS 7 VMware machine:
  config.vm.define "centos72".to_sym do |centos72config|
    centos72config.vm.box = "centos-7.1-amd64-vmware"
    centos72config.vm.hostname = "centos72.local"
    centos72config.vm.network :private_network, ip: "10.0.2.3"
    #Set some machine-specific options for either Virtualbox or VMWare:
    centos72config.vm.provider "virtualbox" do |v|
      #change the amount of RAM
      v.customize ["modifyvm", :id, "--memory", "256"]
      v.gui = false
    end
    config.vm.provider "vmware_fusion" do |v, override|
      #override.vm.provision "shell", inline: "/sbin/ifdown ens33; /sbin/ifup ens33;"
      v.vmx["memsize"] = "256"
      v.vmx["numvcpus"] = "1"
    end
  end

  #A CentOS 7 VMware machine:
  config.vm.define "centos73".to_sym do |centos73config|
    centos73config.vm.box = "centos-7.1-amd64-vmware"
    centos73config.vm.hostname = "centos73.local"
    centos73config.vm.network :private_network, ip: "10.0.2.4"
    #Set some machine-specific options for either Virtualbox or VMWare:
    centos73config.vm.provider "virtualbox" do |v|
      #change the amount of RAM
      v.customize ["modifyvm", :id, "--memory", "256"]
      v.gui = false
    end
    config.vm.provider "vmware_fusion" do |v, override|
      #override.vm.provision "shell", inline: "/sbin/ifdown ens33; /sbin/ifup ens33;"
      v.vmx["memsize"] = "256"
      v.vmx["numvcpus"] = "1"
    end
  end

  config.vm.define "centos6".to_sym do |centos6_config|
    centos6_config.vm.box = "centos-6.6-amd64-vmware"
    centos6_config.vm.hostname = "centos6.local"
    centos6_config.vm.network :private_network, ip: "10.0.2.5"
    #Set some machine-specific options for either Virtualbox or VMWare:
    centos6_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM
      v.customize ["modifyvm", :id, "--memory", "256"]
      v.gui = false
    end
    config.vm.provider "vmware_fusion" do |v, override|
      #override.vm.provision "shell", inline: "sudo /sbin/ifdown ens33; sudo /sbin/ifup ens33;"
      v.vmx["memsize"] = "256"
      v.vmx["numvcpus"] = "1"
    end
    centos6_config.vm.synced_folder ".", "/vagrant", :nfs => true
  end

  config.vm.define "ubuntu".to_sym do |ubuntu_config|
    ubuntu_config.vm.box = "ubuntu-14.04-server-amd64-vmware"
    ubuntu_config.vm.hostname = "ubuntu.local"
    ubuntu_config.vm.network :private_network, ip: "10.0.2.6"
    #Set some machine-specific options for either Virtualbox or VMWare:
    ubuntu_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM
      v.customize ["modifyvm", :id, "--memory", "256"]
      v.gui = false
    end
    config.vm.provider "vmware_fusion" do |v, override|
      #override.vm.provision "shell", inline: "sudo /sbin/ifdown ens33; sudo /sbin/ifup ens33;"
      v.vmx["memsize"] = "256"
      v.vmx["numvcpus"] = "1"
    end
    #ubuntu_config.vm.synced_folder ".", "/vagrant", :nfs => true
  end

end


